app_base/urls.py
from django.contrib import admin
from django.urls import path,include
from app_base import views

urlpatterns = [
    path('',views.home,name='home'),
    path('sample-detail/',views.sample_details, name= 'sample'),
]

hyperProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('app_base.urls','app_base'),namespace='app-base')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_base/models.py
from django.db import models

def sample_image_path(instance,filename):
    return instance.title

class sampleBot(models.Model):
    title = models.CharField(null=True,max_length = 100)
    sample_image = models.ImageField( upload_to='sample_image_path',null=True)
    description = models.TextField(null=True)
    telegram_link = models.CharField(null=True,max_length=50)

    def __str__(self):
        return str(self.title)
class otherSampleBot(models.Model):
    title = models.CharField(null=True,max_length = 100)
    sample_image = models.ImageField( upload_to='sample_image_path',null=True)
    description = models.TextField(null=True)
    telegram_link = models.CharField(null=True,max_length=50)
    def __str__(self):
        return str(self.title)

app_base/views.py
from django.shortcuts import render
from app_base.models import sampleBot,otherSampleBot


def home(request):
    ctx={}
    ctx['sampleBotes'] = sampleBot.objects.all()
    return render(request,'home.html',ctx)

def sample_details(request):
    ctx={}
    ctx['other_sample'] = otherSampleBot.objects.all()
    return render(request,'sample-details.html',ctx)

app_base/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
      <title>HyperDesign</title>
      <!-- CSS  Starter Template - Materialize-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <link href="{% static 'css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
      <style type="text/css">
         @font-face {
         font-family: vazir-medium;
         src: url({% static "font/Farsi-Digits/Vazir-Medium-FD.woff" %});
         }
         @font-face {
         font-family: vazir-bold;
         src: url({% static "font/Farsi-Digits/Vazir-Bold-FD.woff" %});
         }
         @font-face {
         font-family: vazir-thin;
         src: url({% static "font/Farsi-Digits/Vazir-Thin-FD.woff" %});
         }
      </style>
      <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
   </head>
   <body>
      <nav class="light-blue lighten-1" role="navigation">
         <div class="nav-wrapper container">
            <a id="logo-container" class="brand-logo">HyperDesign</a>
            <ul class="right hide-on-med-and-down">
               <li><a class="white-text" href="{% url 'app-base:home' %}#samples">نمونه کار ها </a></li>
               <li><a class="white-text" href="{% url 'app-base:home' %}#about">درباره ی ما </a></li>
               <li><a class="white-text" href="{% url 'app-base:home' %}#download-button">ارتباط با  ما</a></li>
               <li><a href="{% url 'app-base:home' %}">خانه</a></li>
            </ul>
            <ul id="nav-mobile" class="sidenav">
               <li><a href="{% url 'app-base:home' %}">خانه</a></li>
            </ul>
            <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
         </div>
      </nav>
      {% block content %}{% endblock content %}

      <footer class="page-footer blue">
         <div class="container">
            <div class="row">
               <div class="col l6 s12">
                  <h5 class="white-text" id="about">درباره ی تیم ما</h5>
                  <p class="grey-text text-lighten-4">ما یک تیم  هستیم که به صورت تمام وقت بر روی  طراحی و توسعه ی انواع ربات های تلگرامی کار میکنیم و هدف ما توسعه ی کسب و کار و سهولت تبلیغات کار شما در پیام رسان محبوب تلگرام  است.امیدواریم در آینده خدمات ارزنده ی بیشتری در این سایت  به شما عزیزان ارائه بدیم.میتوانید با ما در آیدی HyperDesign@از طریق تلگرام در ارتباط باشید. </p>
               </div>
               <div class="col l6 s12">
                  <h5 class="white-text">محتوا</h5>
                  <ul>
                     <li><a class="white-text" href="{% url 'app-base:home' %}#download-button">ارتباط با  ما</a></li>
                     <li><a class="white-text" href="{% url 'app-base:home' %}#about">درباره ی ما </a></li>
                     <li><a class="white-text" href="{% url 'app-base:home' %}#samples">نمونه کار ها </a></li>
                  </ul>
               </div>
            </div>
         </div>
         <div class="footer-copyright">
            <div class="container">
             توسعه داده شده  توسط <a class="orange-text text-lighten-3">HyperDesign</a>
            </div>
         </div>
      </footer>
      <!--  Scripts-->
      <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script src="{% static 'js/materialize.js' %}"></script>
      <script src="{% static 'js/init.js' %}"></script>
   </body>
</html>

app_base/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% load thumbnail %}
<div class="section no-pad-bot" id="index-banner">
   <div class="container">
      <br><br>
      <h1 class="header center orange-text">Telegram Bot</h1>
      <div class="row center">
         <h4 class="header col s12 light">طراحی و توسعه ی انواع ربات های تلگرامی ساده و  پیشرفته به همراه  امکانات متنوع</h4>
      </div>
      <div class="row center">
         <a href="http://telegram.me/HyperDesign" id="download-button" class="btn-large waves-effect waves-light orange" target="_blank">ارتباط مستقیم  با ما در تلگرام </a>
      </div>
      <br><br>
   </div>
</div>
<div class="container">
   <div class="section">
      <!--   Icon Section   -->
      <div class="row" id="samples">
         <!--start of course row-->
         {%for sampleBot in sampleBotes %}
         <div class="col s12 m4">
            <div class="card">
               <div class="card-image">
                  <!--<img src="{{sampleBot.sample_image.url}}">-->
                  {% thumbnail sampleBot.sample_image "250x240" crop="center" as im %}
                  <img src="{{ im.url }}" class="responsive-img" width="{{ im.width }}" height="{{ im.height }}">
                  {% endthumbnail %}
               </div>
               <div class="card-content">
                  <p>{{sampleBot.description}}</p>
               </div>
               <div class="card-action">
                  <a href="https://telegram.me/{{sampleBot.telegram_link}}" target="_blank">{{sampleBot.telegram_link}}</a>
               </div>
            </div>
         </div>
         {% endfor %}
         <a href="{% url 'app-base:sample' %}"><span  class="more-course">نمونه کارهای بیشتر</span></a>
      </div>
      <!--end of course row-->
   </div>
   <br><br>
</div>
{% endblock content %}

app_base/templates/sample-details.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% load thumbnail %}
<div class="container">
   <div class="section  sample-detail">
      <!--   Icon Section   -->
      <div class="row">
         <!--start of course row-->
         {%for otherSampleBot in other_sample %}
         <div class="col s12 m4">
            <div class="card">
               <div class="card-image">
                  {% thumbnail otherSampleBot.sample_image "250x240" crop="center" as im %}
                  <img src="{{ im.url }}" class="responsive-img" width="{{ im.width }}" height="{{ im.height }}">
                  {% endthumbnail %}
               </div>
               <div class="card-content sample">
                  <p>{{otherSampleBot.description}}</p>
               </div>
               <div class="card-action">
                  <a href="https://telegram.me/{{otherSampleBot.telegram_link}}" target="_blank">{{otherSampleBot.telegram_link}}</a>
               </div>
            </div>
         </div>
         {% endfor %}
      </div>
      <!--end of course row-->
      <div class="warning">
         <h4>قرار دادن ربات های شخصی در سایت به  عنوان  نمونه کار  امکان  پذیر نمی باشد.</h4>
      </div>
   </div>
   <br><br>
</div>
{% endblock content %}